### ISSUE TITLE
WIIM pro support

### ISSUE THREAD

**Issue by infamy** [Velleman/python-linkplay#17]
Most of the other link play libraries and integrations used support the Wiim players. Can that be added to linkplay? Happy to test as I have 2 of the wiim pro.

**Comment by dukeofphilberg** [comment]
If you could test with the open branch https://github.com/Velleman/python-linkplay/tree/create-endpoint-abc that'd be nice, there's some code in `__main__.py` to create a `ClientSession()` that allows unverified SSL.

**Comment by dukeofphilberg** [comment]
Same issue as #19 so we'll close this as we fixup the HomeAssistant integration

**Comment by silamon** [comment]
The pull request went in Home Assistant, closing.
