### ISSUE TITLE
http only supported,. no support for https (used by the wiim devices)

### ISSUE THREAD

**Issue by infamy** [Velleman/python-linkplay#19]
https://github.com/Velleman/python-linkplay/blob/68b43c5892d1c54a61510883ef933b9d74af4a83/src/linkplay/discovery.py#L17

If this was extended to allow passing the protocol, which would allow setting https, this would resolve the issue with wiim devices (or so I suspect). My wiim pro will only respond if it gets a request over https, and ignores http.

**Comment by dukeofphilberg** [comment]
With #27 this should now be possible. The HomeAssistant changes will follow in the coming days.

**Comment by silamon** [comment]
The pull request went in Home Assistant, closing.
