### ISSUE TITLE
Please support the smart speaker which is using Linkplay A98 module to play Youtube media stream

### ISSUE THREAD

**Issue by dinhchinh82** [Velleman/python-linkplay#43]
I just tried to add a smart speaker which using [Linkplay A98 module](https://www.linkplay.com/modules-wifi) to Home Assistant 2024.08 it did not work well.
After adding the speaker to HA, it can show as a media player and Text to Speech works well, can play local mp3 file etc.

By the way, when I tried to play a Youtube song or a playlist, it did not work.
The codec of Youtube media file is "video/mp4; codecs=\"avc1.42001E, mp4a.40.2\".
For speaker using Linkplay A31 module such as Arylic A50, Arylic S10, it works well with Youtube.
So is able to support full feature for speaker which using new Linkplay A98 module?

Thank you.

**Comment by silamon** [comment]
Can you check with the latest version if this is working better? Does it show you discovery of that module? 
Since we don't own every linkplay device, adding support may have to be contributed by the community.

**Comment by dinhchinh82** [comment]
> Can you check with the latest version if this is working better? Does it show you discovery of that module? Since we don't own every linkplay device, adding support may have to be contributed by the community.

could you help me how to test the latest version with this library?

At current, I only know the way to test with Home Assistant.

**Comment by silamon** [comment]
You can upgrade to 2024.9 in which https support was added. Wednesday 2024.10 will come out, but that won't possibly improve this situation.

**Comment by silamon** [comment]
Since there's no comment anymore, I assume you got it to work. 
If you still have an issue with this, feel free to respond to this one and I'll reopen
