### ISSUE TITLE
Cannot select presets greater than 10

### ISSUE THREAD

**Issue by dnikles** [Velleman/python-linkplay#53]
Some linkplay devices support more than 10 presets, but this only allows 10
I think this line is the issue
https://github.com/Velleman/python-linkplay/blob/00817de7ed781475ec7f99d7afeca9f4e3e4ca24/src/linkplay/bridge.py#L166

Using getStatusEx, you can read the value of preset_key to see how many presets the player supports

**Comment by silamon** [comment]
Yeah, a fix is incoming. Thank you for looking into the code. Will close this one when fixed here and then close the HA issue when it's fixed in the integration.
