### ISSUE TITLE
Multiroom join/unjoin does not work

### ISSUE THREAD

**Issue by heinzma** [Velleman/python-linkplay#57]
I am currently testing the latest Home Assistant beta and noticed that it is not possible to join/unjoin devices.

I narrowed it down to this:
https://github.com/Velleman/python-linkplay/blob/855d85ab86b779f6e2b6b9c29916ef44bba37108/src/linkplay/bridge.py#L68-L74

Isn't `DeviceAttribute.ETH_DHCP` a flag for DHCP/Static IP Address?

Furthermore, with my devices (Arylic S10+, EDIFIER MS50A ) there is no `DeviceAttribute.ETH0`. It's `DeviceAttribute.APCLI0` when connected to wifi or `DeviceAttribute.ETH2` (Arylic S10+) when connected to ethernet.
When i change the return value to `self.properties[DeviceAttribute.APCLI0]` it works with my devices.

**Comment by silamon** [comment]
I'll take a look to see. Thank you for testing beta!
