### ISSUE TITLE
Support for devices using https over port 4443

### ISSUE THREAD

**Issue by anderscarling** [Velleman/python-linkplay#66]
Some devices (recent Audio Pro units like the "A10 MkII") expose the linkplay http api over HTTPS on port 4443. As far as I can tell python-linkplay only ever tries to connect on the standard port 443, which fails for these devices.

Would it be possible to implement support for trying multiple https ports?

Linkplay CLI seems to rely on [iterating](https://github.com/ramikg/linkplay-cli/blob/master/linkplay_cli/discovery.py#L38) over a list of potential http ports, defaulting to [only 4443](https://github.com/ramikg/linkplay-cli/blob/master/linkplay_cli/config.py#L11).

## Proof of potential communication

Using client-cert.pem extracted from consts.py I can run `getStatusEx` on my speakers, even though python-linkplay fails to connect to them:

```
$ curl -k -E client-cert.pem 'https://10.10.10.103:4443/httpapi.asp?command=getStatusEx'
{ "language": "en_us", "firmware": "audiopro_a10-user 1.56 1.56 1.56.503670 test-keys", "cast_ver": "1.56. 310669\n", "build": "user", "project": "A10MkII Speaker", "priv_prj": "A10MkII Speaker", .... }
```

## No luck finding a way to auto-discover the port..

I tried to do research a way to resolve what port is being used through the mDNS announcements but is seems to only announce the UPNP port (59512):
<img width="216" alt="image" src="https://github.com/user-attachments/assets/2bcb1391-e540-4524-9ae7-6e3322eb2e97">

The metadata exposed through the UPNP description (in my case `http://10.10.10.103:59152/description.xml`) doesn't seem to include a reference to the linkplay http/https port.

The GetControlDeviceInfoResponse soap response (from soap request to `http://10.10.10.103:59152/upnp/control/rendercontrol1`) gives a Status-field with lots of information about the device - including port used for tcp-uart communications, but no reference to port 4443.

**Comment by silamon** [comment]
It's also what the WiiM Home App does, I decompiled it for your other issue.
